### ISSUE TITLE
[BUG] error message in output.log when logo not found / no logo available

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1461]
**Describe the bug**
One of my teams in my league does not have a logo. Apparently this lead to an error message in the output.log.

**To Reproduce**
1. Go to 'League Data tab'
2. Download match from a team that has no logo (aka click red arrow symbol next to that match)
3. Upgraded version v270 to to v273
4. Opened application
5. Look at the output.log

**Screenshots**
12:23:58 [Info]    core.HO: VERSION: 6.0   versionType:  DEV   RevisionNumber: 273
12:24:00 [Info]    core.model.HOVerwaltung: language used for interface is: Nederlands
12:24:00 [Info]    core.training.TrainingWeekManager: Next week training date: 2022-04-15 01:05:00
12:24:00 [Info]    core.gui.HOMainFrame: This is HO! version 6.0 DEV (r273), have fun!
12:24:00 [Info]    core.gui.HOMainFrame: Operating system found: Windows 10 on amd64 (10.0)
12:24:00 [Info]    core.gui.HOMainFrame: Using java: 17.0.1 (Eclipse Adoptium)
12:24:04 [Error]   core.db.TeamsLogoTable: logo information not available in database for team ID=365613
12:24:04 [Error]   core.gui.theme.ThemeManager: logo not found for team 365613
12:24:04 [Error]   core.db.TeamsLogoTable: logo information not available in database for team ID=365613
12:24:04 [Error]   core.gui.theme.ThemeManager: logo not found for team 365613

Below is a screenshot that I took in the previous version where the match download does not finish for that team ("please wait...." and orange completion bar stalls at 50%).
Don't know if it is related or not. 
![TEST DOWNLOAD MATCH](https://user-images.githubusercontent.com/102049050/163561700-59de74b4-dff4-4889-a9e5-e6468f10267d.jpg)

**Platform information:**
 - OS: 10
- Version 6.0 v273

**Additional context**
Seems to me that it is correct that logo is not found, so that should not produce an error meesage in the lock.

**Comment by masterpatje** [comment]
Tried to reproduce it.
Clicking O.N.S. Sneek - Stator match 
Image is the situation **after** I clicked it. It did not stop at 50% and completed.
![image](https://user-images.githubusercontent.com/102049050/163563000-d5963038-c81e-4115-a67c-2e46bdc97ea9.png)

But again got some usefull error output:
 [Error]   TeamsLogoTable: logo information not available in database for team ID=365613
 [Error]   ThemeManager: logo not found for team 365613
 [Error]   MyConnector: Failed to select a proxy
java.io.IOException: Failed to select a proxy
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1234)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at com.github.scribejava.core.httpclient.jdk.JDKHttpClient.doExecute(JDKHttpClient.java:138)
	at com.github.scribejava.core.httpclient.jdk.JDKHttpClient.execute(JDKHttpClient.java:94)
	at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:114)
	at core.net.MyConnector.getNonCHPPWebFile(MyConnector.java:764)
	at core.net.MyConnector.getFileFromWeb(MyConnector.java:649)
	at tool.updater.UpdateHelper.download(UpdateHelper.java:26)
	at core.db.TeamsLogoTable.getTeamLogoFileName(TeamsLogoTable.java:87)
	at core.db.DBManager.getTeamLogoFileName(DBManager.java:2612)
	at core.gui.theme.ThemeManager.getClubLogo(ThemeManager.java:191)
	at core.gui.theme.ThemeManager.getSmallClubLogo(ThemeManager.java:182)
	at module.series.SeriesTablePanel.populateSerieTable(SeriesTablePanel.java:260)
	at module.series.SeriesTablePanel.changeSaison(SeriesTablePanel.java:98)
	at module.series.SeriesPanel.informSaisonChange(SeriesPanel.java:136)
	at module.series.SeriesPanel.fillSaisonCB(SeriesPanel.java:132)
	at module.series.SeriesPanel.initialize(SeriesPanel.java:35)
	at core.gui.comp.panel.LazyImagePanel.callInitialize(LazyImagePanel.java:145)
	at core.gui.comp.panel.LazyImagePanel$2.hierarchyChanged(LazyImagePanel.java:132)
	at java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6793)
	at java.desktop/java.awt.Component.processEvent(Component.java:6412)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.Component.createHierarchyEvents(Component.java:5639)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1474)
	at java.desktop/java.awt.Component.show(Component.java:1691)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/javax.swing.JComponent.setVisible(JComponent.java:2720)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:422)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:295)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:148)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:79)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:648)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:623)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:4101)
	at java.desktop/javax.swing.plaf.synth.SynthTabbedPaneUI$1.mousePressed(SynthTabbedPaneUI.java:320)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: protocol = https host = null
	at java.base/sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:186)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	... 79 more

 [Debug]   UpdateHelper: Error downloading from 'https:http://res.hattrick.org/teamlogo/11/101/1010/1009780/1009780.png': java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read()" because "in" is null
 [Error]   TeamsLogoTable: error when trying to download logo of team ID: 1009780
https:http://res.hattrick.org/teamlogo/11/101/1010/1009780/1009780.png
 [Error]   ThemeManager: logo not found for team 1009780
 [Error]   MyConnector: Failed to select a proxy
java.io.IOException: Failed to select a proxy
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1234)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at com.github.scribejava.core.httpclient.jdk.JDKHttpClient.doExecute(JDKHttpClient.java:138)
	at com.github.scribejava.core.httpclient.jdk.JDKHttpClient.execute(JDKHttpClient.java:94)
	at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:114)
	at core.net.MyConnector.getNonCHPPWebFile(MyConnector.java:764)
	at core.net.MyConnector.getFileFromWeb(MyConnector.java:649)
	at tool.updater.UpdateHelper.download(UpdateHelper.java:26)
	at core.db.TeamsLogoTable.getTeamLogoFileName(TeamsLogoTable.java:87)
	at core.db.DBManager.getTeamLogoFileName(DBManager.java:2612)
	at core.gui.theme.ThemeManager.getClubLogo(ThemeManager.java:191)
	at core.gui.theme.ThemeManager.getSmallClubLogo(ThemeManager.java:182)
	at module.series.SeriesTablePanel.populateSerieTable(SeriesTablePanel.java:260)
	at module.series.SeriesTablePanel.changeSaison(SeriesTablePanel.java:98)
	at module.series.SeriesPanel.informSaisonChange(SeriesPanel.java:136)
	at module.series.SeriesPanel.fillSaisonCB(SeriesPanel.java:132)
	at module.series.SeriesPanel.initialize(SeriesPanel.java:35)
	at core.gui.comp.panel.LazyImagePanel.callInitialize(LazyImagePanel.java:145)
	at core.gui.comp.panel.LazyImagePanel$2.hierarchyChanged(LazyImagePanel.java:132)
	at java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6793)
	at java.desktop/java.awt.Component.processEvent(Component.java:6412)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.Component.createHierarchyEvents(Component.java:5639)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1474)
	at java.desktop/java.awt.Component.show(Component.java:1691)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/javax.swing.JComponent.setVisible(JComponent.java:2720)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:422)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:295)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:148)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:79)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:648)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:623)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:4101)
	at java.desktop/javax.swing.plaf.synth.SynthTabbedPaneUI$1.mousePressed(SynthTabbedPaneUI.java:320)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: protocol = https host = null
	at java.base/sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:186)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	... 79 more

 [Debug]   UpdateHelper: Error downloading from 'https:http://res.hattrick.org/teamlogo/6/51/509/508809/508809.png': java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read()" because "in" is null
 [Error]   TeamsLogoTable: error when trying to download logo of team ID: 508809
https:http://res.hattrick.org/teamlogo/6/51/509/508809/508809.png
 [Error]   ThemeManager: logo not found for team 508809
 [Error]   MyConnector: Failed to select a proxy
java.io.IOException: Failed to select a proxy
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1234)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at com.github.scribejava.core.httpclient.jdk.JDKHttpClient.doExecute(JDKHttpClient.java:138)
	at com.github.scribejava.core.httpclient.jdk.JDKHttpClient.execute(JDKHttpClient.java:94)
	at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:114)
	at core.net.MyConnector.getNonCHPPWebFile(MyConnector.java:764)
	at core.net.MyConnector.getFileFromWeb(MyConnector.java:649)
	at tool.updater.UpdateHelper.download(UpdateHelper.java:26)
	at core.db.TeamsLogoTable.getTeamLogoFileName(TeamsLogoTable.java:87)
	at core.db.DBManager.getTeamLogoFileName(DBManager.java:2612)
	at core.gui.theme.ThemeManager.getClubLogo(ThemeManager.java:191)
	at core.gui.theme.ThemeManager.getSmallClubLogo(ThemeManager.java:182)
	at module.series.SeriesTablePanel.populateSerieTable(SeriesTablePanel.java:260)
	at module.series.SeriesTablePanel.changeSaison(SeriesTablePanel.java:98)
	at module.series.SeriesPanel.informSaisonChange(SeriesPanel.java:136)
	at module.series.SeriesPanel.fillSaisonCB(SeriesPanel.java:132)
	at module.series.SeriesPanel.initialize(SeriesPanel.java:35)
	at core.gui.comp.panel.LazyImagePanel.callInitialize(LazyImagePanel.java:145)
	at core.gui.comp.panel.LazyImagePanel$2.hierarchyChanged(LazyImagePanel.java:132)
	at java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6793)
	at java.desktop/java.awt.Component.processEvent(Component.java:6412)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.Component.createHierarchyEvents(Component.java:5639)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1474)
	at java.desktop/java.awt.Component.show(Component.java:1691)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/javax.swing.JComponent.setVisible(JComponent.java:2720)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:422)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:295)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:148)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:79)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:648)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:623)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:4101)
	at java.desktop/javax.swing.plaf.synth.SynthTabbedPaneUI$1.mousePressed(SynthTabbedPaneUI.java:320)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: protocol = https host = null
	at java.base/sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:186)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	... 79 more

 [Debug]   UpdateHelper: Error downloading from 'https:http://res.hattrick.org/teamlogo/13/128/1278/1277381/1277381.png': java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read()" because "in" is null
 [Error]   TeamsLogoTable: error when trying to download logo of team ID: 1277381
https:http://res.hattrick.org/teamlogo/13/128/1278/1277381/1277381.png
 [Error]   ThemeManager: logo not found for team 1277381
 [Debug]   OnlineWorker: Get Lineup : 694456451
 [Debug]   TeamsLogoTable: storeTeamLogoInfo: logo URI was null for team 365613
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Error]   TeamsLogoTable: logo information not available in database for team ID=365613
 [Error]   ThemeManager: logo not found for team 365613
 [Error]   TeamsLogoTable: logo information not available in database for team ID=365613
 [Error]   ThemeManager: logo not found for team 365613
 [Error]   TeamsLogoTable: logo information not available in database for team ID=365613
 [Error]   ThemeManager: logo not found for team 365613

**Comment by masterpatje** [comment]
The following match is not finished:
![image](https://user-images.githubusercontent.com/102049050/163563517-fb814312-a20a-427e-888a-0f7b99eb12df.png)
![image](https://user-images.githubusercontent.com/102049050/163563587-ab363cce-7cd1-4fb5-a7db-8d1b134dc579.png)

And the following output is generated. The mentioned team ID=365613 is O.N.S. Sneek, so I am a bit unsure why that is, because I download the match Poznan - Asteria?!

Maybe interferring problem with O.N.S. Sneek match I downloaded before?

13:00:14 [Error]   core.db.TeamsLogoTable: logo information not available in database for team ID=365613
13:00:14 [Error]   core.gui.theme.ThemeManager: logo not found for team 365613
13:00:31 [Error]   core.db.TeamsLogoTable: logo information not available in database for team ID=365613
13:00:31 [Error]   core.gui.theme.ThemeManager: logo not found for team 365613
13:00:32 [Error]   core.db.TeamsLogoTable: logo information not available in database for team ID=365613
13:00:32 [Error]   core.gui.theme.ThemeManager: logo not found for team 365613
13:00:32 [Error]   core.db.TeamsLogoTable: logo information not available in database for team ID=365613
13:00:32 [Error]   core.gui.theme.ThemeManager: logo not found for team 365613
13:00:32 [Error]   core.db.TeamsLogoTable: logo information not available in database for team ID=365613
13:00:32 [Error]   core.gui.theme.ThemeManager: logo not found for team 365613

**Comment by wsbrenk** [comment]
commit will fix some logo download issues and changes log level from ERROR to DEBUG when teams have no logo.

**Comment by masterpatje** [comment]
**Errors in output.log are fixed, but..**

After clicking the Sporting Poznan - Asteria match it seems that it correctly gets the data, but I get the message "please wait..." and orange bar that doesn't complete.
And the following output is generated to the output.log

![image](https://user-images.githubusercontent.com/102049050/163711415-0996f5e9-11b2-4955-a307-3cfd83a247cd.png)

[Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   OnlineWorker: Get Lineup : 688688822
 [Debug]   OnlineWorker: Get Lineup : 690594140
 [Debug]   OnlineWorker: Get Lineup : 690730964
 [Debug]   OnlineWorker: Get Lineup : 690787141
 [Debug]   OnlineWorker: Get Lineup : 690946633
 [Debug]   OnlineWorker: Get Lineup : 691022449
 [Debug]   OnlineWorker: Get Lineup : 694456449
 [Debug]   OnlineWorker: Get Lineup : 695131019
 [Debug]   OnlineWorker: Get Lineup : 694456454
 [Debug]   TeamsLogoTable: storeTeamLogoInfo: logo URI was null for team 365613
 [Debug]   OnlineWorker: Get Lineup : 695315582
 [Debug]   OnlineWorker: Get Lineup : 694456459
 [Debug]   OnlineWorker: Get Lineup : 694456462
 [Debug]   OnlineWorker: Get Lineup : 694456467
 [Debug]   OnlineWorker: Get Lineup : 694456470
 [Debug]   OnlineWorker: Get Lineup : 694456471
 [Debug]   OnlineWorker: Get Lineup : 694456479
 [Debug]   OnlineWorker: Get Lineup : 694456482
 [Debug]   OnlineWorker: Get Lineup : 694456485
 [Debug]   OnlineWorker: Get Lineup : 694456491
 [Debug]   OnlineWorker: Get Lineup : 694456494
 [Debug]   OnlineWorker: Get Lineup : 694456499
 [Debug]   TeamsLogoTable: storeTeamLogoInfo: logo URI was null for team 365613
 [Debug]   OnlineWorker: Get Lineup : 694456505
 [Info]    TrainingWeekManager: Next week training date: 2022-04-22 01:05:00
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Debug]   MatchRoleID: Position not recognized: -1
 [Debug]   MatchRoleID: Position not recognized: -1
 [Debug]   MatchRoleID: Position not recognized: -1
 [Debug]   TeamsLogoTable: team with no logo team ID=365613
 [Debug]   ThemeManager: logo not found for team 365613
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Info]    TrainingWeekManager: Next week training date: 2022-04-22 01:05:00
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Info]    TrainingWeekManager: Next week training date: 2022-04-22 01:05:00
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Info]    TrainingWeekManager: Next week training date: 2022-04-22 01:05:00
 [Debug]   TrainingModel: Previous training date: TrainingPerWeek[Training date: 2022-04-15 01:05:00, Training Type: Playmaking%, Intensity: 100%, StaminaPart: 17]
 [Debug]   FutureTrainingTable: FutureTraining table has been cleared !
 [Debug]   TeamsLogoTable: team with no logo team ID=365613
 [Debug]   ThemeManager: logo not found for team 365613
 [Debug]   TeamsLogoTable: team with no logo team ID=365613
 [Debug]   ThemeManager: logo not found for team 365613
 [Debug]   TeamsLogoTable: team with no logo team ID=365613
 [Debug]   ThemeManager: logo not found for team 365613
 [Debug]   OnlineWorker: Get Lineup : 694456450
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Debug]   TeamsLogoTable: team with no logo team ID=365613
 [Debug]   ThemeManager: logo not found for team 365613
 [Debug]   TeamsLogoTable: team with no logo team ID=365613
 [Debug]   ThemeManager: logo not found for team 365613
 [Debug]   TeamsLogoTable: team with no logo team ID=365613
 [Debug]   ThemeManager: logo not found for team 365613

**Comment by masterpatje** [comment]
After clicking the ONS Sneek - Stator match it seems that it correctly gets the data, but I get the message "please wait..." and orange bar filled a bit more from last comment but still doesn't complete.
I added the output that was generated to the output.log

![image](https://user-images.githubusercontent.com/102049050/163711614-3b3a4d05-912b-432d-8e86-db79b431d250.png)

[Debug]   OnlineWorker: Get Lineup : 694456451
 [Debug]   TeamsLogoTable: storeTeamLogoInfo: logo URI was null for team 365613
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Debug]   TeamsLogoTable: team with no logo team ID=365613
 [Debug]   ThemeManager: logo not found for team 365613
 [Debug]   TeamsLogoTable: team with no logo team ID=365613
 [Debug]   ThemeManager: logo not found for team 365613
 [Debug]   TeamsLogoTable: team with no logo team ID=365613
 [Debug]   ThemeManager: logo not found for team 365613

**Comment by masterpatje** [comment]
@wsbrenk I am unsure if in the newest update this problem is fixed. 

Do you want me to test it again?

**Comment by wsbrenk** [comment]
@masterpatje please wait is still not fixed - only the team logo errors are handled for now.

**Comment by masterpatje** [comment]
Fixed. Working properly in v284.
