### ISSUE TITLE
[BUG]Former Coach click on him and an Error Occured

### ISSUE THREAD

**Issue by zigmond** [akasolace/HO#597]
**Describe the bug**
I changed, left the old one in the squad, when I click on him on squad tab I get an error occured
Copid from the log details

java.lang.NullPointerException
	at module.playerOverview.SpielerDetailPanel.setLabels(SpielerDetailPanel.java:368)
	at module.playerOverview.SpielerDetailPanel.setSpieler(SpielerDetailPanel.java:275)
	at module.playerOverview.SpielerUebersichtsPanel.setPlayer(SpielerUebersichtsPanel.java:56)
	at core.gui.HOMainFrame.setActualSpieler(HOMainFrame.java:292)
	at module.lineup.LineupPanel$1.synchronizeSelection(LineupPanel.java:265)
	at module.lineup.LineupPanel$1.valueChanged(LineupPanel.java:242)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
	at javax.swing.JTable.setRowSelectionInterval(Unknown Source)
	at module.lineup.LineupPanel$1.synchronizeSelection(LineupPanel.java:261)
	at module.lineup.LineupPanel$1.valueChanged(LineupPanel.java:244)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
	at javax.swing.JTable.setRowSelectionInterval(Unknown Source)
	at module.playerOverview.SpielerUebersichtNamenTable.setSpieler(SpielerUebersichtNamenTable.java:45)
	at module.lineup.LineupPanel.setPlayer(LineupPanel.java:63)
	at core.gui.HOMainFrame.setActualSpieler(HOMainFrame.java:291)
	at module.playerOverview.SpielerUebersichtsPanel.lambda$addTableSelectionListeners$2(SpielerUebersichtsPanel.java:261)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
	at javax.swing.JTable.changeSelectionModel(Unknown Source)
	at javax.swing.JTable.changeSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Screenshots**

**Platform information:**
 - OS: [Windows 8

**Comment by akasolace** [comment]
can you please put here a copy of your db ?  thank you

**Comment by zigmond** [comment]
Thank you

I Attach the current hrf, I hope that is what you mean, if not, let me know
please :)

Diolch

Zig

**Comment by akasolace** [comment]
@zigmond  I would prefer if you:
      - make a copy your db folder
      - make a zip of the db copy
      - use https://send.firefox.com/ to share it
      - paste the link here

Thank you

**Comment by zigmond** [comment]
Hope this is what you are asking for, if not, please let me know
Diolch :)
https://send.firefox.com/download/e99b3e81e27ec7a6/#6IC9QhaLPrRitz2T0QwUog


Zig

**Comment by akasolace** [comment]
perfect thank you !

**Comment by yaute74** [comment]
somebody download the db ? the link has expired :(

**Comment by akasolace** [comment]
@yaute74 let me check

**Comment by zigmond** [comment]
If not, let me please know I'll zip it again and send a link :)

Diolch!

Zig

**Comment by yaute74** [comment]
The database seem to by corrupt (I also try the backup):
![image](https://user-images.githubusercontent.com/34601782/85620419-0c71f080-b664-11ea-9a54-337da19e8506.png)
is the second time we have this problem...
@akasolace do you make some tests on your side ?
@zigmond do you have a backup of your hrf ?

**Comment by akasolace** [comment]
@yaute74 no and my PC is now on a box so I won't touch HO for almost 2 weeks I guess ....
@zigmond you said you still have a working DB under 2.1?
@yaute74 if that is the case it is easy to convert it for 3.0 we know what caused the bug....We wil lstill have to implement the solution inside HO! (at the enf of the list of @tychobrailleur)

**Comment by akasolace** [comment]
@yaute74  I guess the title of the issue is not correct ... it is a data corruption.  This happens upgrading from 2.0 to 3.0 when some null entries were not converted to default value before index creation

**Comment by yaute74** [comment]
At start @zigmond had two problems:
- null pointer on coach
- performance issue with update

On his side he can start HO with his database, not me.

@akasolace so when can do nothing for that ?

**Comment by akasolace** [comment]
> On his side he can start HO with his database, not me.  

That part I don't understand.... @zigmond the db you shared with us, you can open it in 3.0?  Or do you kept your 2.1 install which is still working?

> @akasolace so when can do nothing for that ?

We have no solution for db which reach that level of corruption, we can't even open them. For other db which are corrupted -  easy to recognize because the .data is stuck to date of upgrade and only the .backup is updated.  Those dbs are I think at risk of fatal corruption. For those we can fix the issues. I did it on a branch but @tychobrailleur took the lead on this and build a dedicated tool. The idea would be at some point to have this tool as part of HO!

It is potentially a severe issue, I don't know how many users have corrupted db (it could potentially be a lot) and I don't know what cause some of those DB to go to a fatal state.

**Comment by yaute74** [comment]
ok thank for the info

**Comment by zigmond** [comment]
I can't open 4.0.
I tried to copy the database from 2.1 that is working to 4.0 and still no
joy with 4.0

Zig

**Comment by yaute74** [comment]
@zigmond  If you have the db in version 2.1, it could be interesting to do some migration tests. Can you share it ?

**Comment by akasolace** [comment]
Yes definitely ... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zigmond** [comment]
https://send.firefox.com/download/f35d6066b84dfb47/#Cz1zpxcCACn81YjhSiBoYA

Diolch :)

**Comment by tychobrailleur** [comment]
@yaute74 You don't happen to have @zigmond 's db?  Firefox Send seems to be AWOL at the minute.  

Go raibh maith agat! (=

**Comment by yaute74** [comment]
@tychobrailleur  I have only this https://drive.google.com/file/d/1FLB5JmW6qlz1dMucKhTWTgaW-AEPgjAu/view?usp=sharing

**Comment by tychobrailleur** [comment]
I tried the repair tool, but it fails because the db is prior to version 3.0.

I was not planning to migrate across versions, but one thing I can do is to add an option that repairs using the same schema as the source schema (if it can be recovered).  Migration would then be left to HO.

**Comment by akasolace** [comment]
@tychobrailleur if I understand corrctly,  the db of @zigmond is functional under 2.1 but breaks if he upgrades to 4.0. 
We don't know if:
    - the db is corrupted but still functioning in 2.1 but the upgade to 4.0 makes it non functioning
    - the db is sane but upgrading to 4.0 breaks it

Your DB repair tool cannot work on the 2.1 db (it assumes table definition from 4.0) 

Is that correct ?

  - Have you tried the DB repair tool on corrupted db after 4.0 upgrade? 

> I was not planning to migrate across versions, but one thing I can do is to add an option that repairs using the same schema as the source schema (if it can be recovered). Migration would then be left to HO.

Yes this what I had in minf, it shoud work but the remaining point would be to replace null values for columns that are used in indexed or have been declared as non null down the road, this could be done by your tool but it would be much better to do it in DBUpdater

**Comment by tychobrailleur** [comment]
To clarify:

- The db version set in the current db is 2.1
- It is corrupt – the telltale sign is usually an OOME such as:

```
Jul 28, 2020 6:04:05 P.M. org.hsqldb.persist.Logger logSevereEvent
SEVERE: /tmp/db/database.data getFromFile failed 35
org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
```
- I have changed the repair tool to add a `current` option to import in the same schema.  This re-imported most of the data of the corrupt db into a new db (except data from the corrupt table, the repair tool cannot do anything about this)
- HO 4.x starts ok with the "repaired" db, which is then migrated ok to the current version (in the case of this db, players data seems to be what's corrupt, so a new download is needed).


> it shoud work but the remaining point would be to replace null values for columns that are used in indexed or have been declared as non null down the road

It [handles](https://github.com/tychobrailleur/hodb-repair/blob/master/src/main/java/io/github/hodev/dbrepair/App.java#L150) that already when migrating to the correct version (4.0.0).

**Comment by zigmond** [comment]
Just copied my current DB from 2.1 to 4.0 and launched it, it did start,
updated the DB, took again more than 5 minutes to update, still same
problem with the former coach.

Just to update you guys

Thanks

Zig

**Comment by akasolace** [comment]
@tychobrailleur ok so the inital db was already corrupted, and he was using 2.1, so nothing bad we did recently.
Your tool seems to do a very good job and then HO migrates it correcty to 4.0 which is perfect. The thing I would like to clarify is the conversion of null values. If I understand correctly your tool would do it when repairing a db but HO needs also to implement it, right ? 
I mean assuming a db version 2.1 having null values in columns A and B but only A declared as non null in the schema.
Your tool will replace the null values in column A and we get a repaired DB 2.1 version.  Now HO upgrade it to 4.0, at some point in the update it create an index using B, but B still contains null values so it breaks the DB. The fault would be in HO because at some point in the past we created index or declared non nul colum on column which already had null values. HSQLD instead of throwing an error silently breaks the table ...

**Comment by tychobrailleur** [comment]
> still same problem with the former coach. Just to update you guys Thanks Zig

Yes, sorry Zig, I don't think that particular issue has been fixed yet. 😃

@akasolace the db tool is not that smart (yet?), I need to explicitly tell what column in what version of the db needs to be "de-nullified."  Quite feasible, this would require more work.

**Comment by akasolace** [comment]
> @akasolace the db tool is not that smart (yet?), I need to explicitly tell what column in what version of the db needs to be "de-nullified." Quite feasible, this would require more work.

maybe we can be brutal and denullify all values ... but we might suffer side effects ...

**Comment by zigmond** [comment]
Hi Guys
Just bought a new player (well, he is old, 39) and again, on HO! V 4 I get
the same, as soon as I click on him, can't even change the information for
him on the rolldown for Best Position

java.lang.NullPointerException
at
module.playerOverview.SpielerDetailPanel.setLabels(SpielerDetailPanel.java:368)
at
module.playerOverview.SpielerDetailPanel.setSpieler(SpielerDetailPanel.java:275)
at
module.playerOverview.SpielerUebersichtsPanel.setPlayer(SpielerUebersichtsPanel.java:56)
at core.gui.HOMainFrame.setActualSpieler(HOMainFrame.java:292)
at module.lineup.LineupPanel$1.synchronizeSelection(LineupPanel.java:265)
at module.lineup.LineupPanel$1.valueChanged(LineupPanel.java:242)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown
Source)
at javax.swing.JTable.setRowSelectionInterval(Unknown Source)
at module.lineup.LineupPanel$1.synchronizeSelection(LineupPanel.java:261)
at module.lineup.LineupPanel$1.valueChanged(LineupPanel.java:244)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown
Source)
at javax.swing.JTable.setRowSelectionInterval(Unknown Source)
at
module.playerOverview.SpielerUebersichtNamenTable.setSpieler(SpielerUebersichtNamenTable.java:45)
at module.lineup.LineupPanel.setPlayer(LineupPanel.java:63)
at core.gui.HOMainFrame.setActualSpieler(HOMainFrame.java:291)
at
module.playerOverview.SpielerUebersichtsPanel.lambda$addTableSelectionListeners$2(SpielerUebersichtsPanel.java:261)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown
Source)
at javax.swing.JTable.setRowSelectionInterval(Unknown Source)
at
module.playerOverview.SpielerUebersichtsPanel.selectRow(SpielerUebersichtsPanel.java:236)
at
module.playerOverview.SpielerUebersichtsPanel.lambda$addTableSelectionListeners$1(SpielerUebersichtsPanel.java:249)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown
Source)
at javax.swing.JTable.changeSelectionModel(Unknown Source)
at javax.swing.JTable.changeSelection(Unknown Source)
at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(Unknown
Source)
at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(Unknown Source)
at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown
Source)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown
Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown
Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)

Hope it helps.

**Comment by akasolace** [comment]
Hi @zigmond,

Sorry for the late feedback but I would like to have now a look at your issue as we are getting closer to a 4.0 releae.  

First, just to clarify, could you please confirm or correct the following:
  - you still have a HO 2.1 version which is working fine ? Could you share again with me your db (I am sorry but all the links above have expired) 
  - upgrading to HO 4.0 "works" but then you have issue like the one you described "click on some player to change best position throws error"?

Thank you

**Comment by zigmond** [comment]
Hi :)

Yes on both.

Which d/b would you like :)

Zig

**Comment by akasolace** [comment]
I would need only a copy of the working 2.1 database ....

**Comment by zigmond** [comment]
Firefox Send is temporarily unavailable while we work on product
improvements.

We appreciate your patience while we make the Firefox Send experience
better.


How else can I do it ?

**Comment by akasolace** [comment]
> How else can I do it ?

plenty of choice but for exampe:

 - https://send.tresorit.com/

 - https://gofile.io/

**Comment by zigmond** [comment]
https://send.tresorit.com/a#XFoKGnR5uNo6juFHXTbfMw

Hope this is ok

**Comment by akasolace** [comment]
ok thank you ... I will have a first look later today

**Comment by zigmond** [comment]
Let me know if there is anything else I can do :)

**Comment by zigmond** [comment]
Just noticed now that the Supporter Spec player (Mark Woaks) have the
problem now as well

java.lang.NullPointerException
at
module.playerOverview.SpielerDetailPanel.setLabels(SpielerDetailPanel.java:368)
at
module.playerOverview.SpielerDetailPanel.setSpieler(SpielerDetailPanel.java:275)
at
module.playerOverview.SpielerUebersichtsPanel.setPlayer(SpielerUebersichtsPanel.java:56)
at core.gui.HOMainFrame.setActualSpieler(HOMainFrame.java:292)
at module.lineup.LineupPanel$1.synchronizeSelection(LineupPanel.java:265)
at module.lineup.LineupPanel$1.valueChanged(LineupPanel.java:242)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown
Source)
at javax.swing.JTable.setRowSelectionInterval(Unknown Source)
at module.lineup.LineupPanel$1.synchronizeSelection(LineupPanel.java:261)
at module.lineup.LineupPanel$1.valueChanged(LineupPanel.java:244)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown
Source)
at javax.swing.JTable.setRowSelectionInterval(Unknown Source)
at
module.playerOverview.SpielerUebersichtNamenTable.setSpieler(SpielerUebersichtNamenTable.java:45)
at module.lineup.LineupPanel.setPlayer(LineupPanel.java:63)
at core.gui.HOMainFrame.setActualSpieler(HOMainFrame.java:291)
at
module.playerOverview.SpielerUebersichtsPanel.lambda$addTableSelectionListeners$2(SpielerUebersichtsPanel.java:261)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown
Source)
at javax.swing.JTable.changeSelectionModel(Unknown Source)
at javax.swing.JTable.changeSelection(Unknown Source)
at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(Unknown
Source)
at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(Unknown Source)
at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown
Source)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown
Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown
Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)

Not sure if it is related.

Zig :)

**Comment by akasolace** [comment]
> Just noticed now that the Supporter Spec player (Mark Woaks) have the
problem now as well

you have this as soon as you select him ?  if you click on the row on palyer overview for example.... ?

**Comment by zigmond** [comment]
As soon as I click is line.
I can't change his "best position" manually for example :)
I can continue to other players, but I can't change him :)

**Comment by wsbrenk** [comment]
@akasolace isn't commit 21ead5fb4000c559c7a94a4048a1acfc252e1b3e a solution of this issue?

**Comment by akasolace** [comment]
@zigmond yesterday I had a first quick look, I can confirm the db seems to work fine in 2.1 and I can also confirm the upgrade to 4.0 is failing. I had error message when launching 4.0. I am not sure yet of what is happening but I don't think the issue is with the database. I will try to investigate further later today.

**Comment by zigmond** [comment]
Thank you mate.

I have no problem launching and downloading database on 4.0 at all, it's
only when I click (stand on the line) of the former coach now regular
player (though eternally injured) and the Support player that I get those
errors

Saying that, I just relaunched it and the supporter player is ok, so it is
just the former coach.

Out of memory, I have 2 supporter players, and only the one had a problem,
the 2nd one was fine.

Hope it makes sense

Zig :)

**Comment by akasolace** [comment]
@zigmond this is strange me I can't even launch HO! 4.0 after the database upgrade ...

**Comment by akasolace** [comment]
@zigmond with 2.1 it crashed if I click on Matches tab, you don't have the same ?

![image](https://user-images.githubusercontent.com/1136496/92145639-d053cc80-ee18-11ea-98f9-ce27bd7ed1de.png)

**Comment by zigmond** [comment]
Never really used it for that, but, yes, it does bring the error, not with
4.0 though, it does get to the matches tab

**Comment by akasolace** [comment]
@zigmond  I think I fixed the issue
@tychobrailleur I could submit a PR but I have plenty of warnings from darklarf and I can't find what cause this. Do you have any clue ?

![image](https://user-images.githubusercontent.com/1136496/92149124-de581c00-ee1d-11ea-82a8-348b1cb7cb20.png)
